//requiring path and fs modules
const path = require("path");
const fs = require("fs");
const folderRawForms = "./raw_forms/fo";
const folderInputForms = "./input_forms/fo";
const pathRawForms = path.join(__dirname, folderRawForms);
const pathInputForms = path.join(__dirname, folderInputForms);


/**
 * Checks if a given `formId` represents a valid file type FO.
 *
 * @param {string} formId - The form id want to validate.
 * @returns {boolean} - `true` if the `formId` is considered a valid form type (i.e., it's NOT in the list of invalid types);
 * `false` if the `formId` is found in the list of invalid types.
 */
function isValidFormFO(formId) {
    const invalidformTypeArray = [
        "lookup",
        "posting",
        "O9_FEE",
        "ifccd",
        "pgoacc",
        "cibnk",
        "pgacc",
        "cifccd",
        "cbrcdc",
        "cctmcd",
        "cncat",
        "isiccd",
        "spl",
        "actgrp",
        "plcd",
        "usrcd",
        "sacno",
        "pdacc",
        "crnum",
        "pdoacc",
        "pdmacc",
        "ctlid",
        "Posting",
        "cbrid",
        "management",
        "crbank",
        "msgcode",
        "racno",
        "cnostro",
        "crbank3",
        "ctxg3",
        "ctxg4",
        "dlid",
        "pcacc",
        "benefbnk",
        "catcd",
        "ctrcd",
        "hcacc",
        "paybnk",
        "recacc",
        "rembnk",
        "payacc",
        "ifc",
        "cfrbnk",
        "issbnk",
        "splnm",
        "newhcacc",
        "advbnk",
        "pmtacc",
        "_SO",
        "_so"
    ]
    const containsInvalidType = invalidformTypeArray.some(invalidType => formId.includes(invalidType));
    return !containsInvalidType;
}

const formDataChange = fs
    .readdirSync(pathRawForms, { withFileTypes: true })
    .map((el) => el.name);
const mainFormIdPrefixes = [
    "FO_ACT_CPAC",
    "FO_ACT_CVS",
    "FO_ACT_EVAL",
    "FO_ACT_FEE",
    "FO_ACT_GFEE",
    "FO_ACT_NGL",
    "FO_ADM_FXD",
    "FO_ADM_FXR",
    "FO_ADM_JOB",
    "FO_CRD_AIPV",
    "FO_CRD_APIFC",
    "FO_CRD_APR",
    "FO_CRD_BLK",
    "FO_CRD_CAS",
    "FO_CRD_CDR",
    "FO_CRD_CHD",
    "FO_CRD_CIPM",
    "FO_CRD_CLA",
    "FO_CRD_CLS",
    "FO_CRD_EXT",
    "FO_CRD_FCD",
    "FO_CRD_FCG",
    "FO_CRD_FOC",
    "FO_CRD_FRG",
    "FO_CRD_GSCH",
    "FO_CRD_HIS",
    "FO_CRD_IFC",
    "FO_CRD_IHIS",
    "FO_CRD_IPCT",
    "FO_CRD_MDR",
    "FO_CRD_MIC",
    "FO_CRD_MIPM",
    "FO_CRD_NPL",
    "FO_CRD_OPN",
    "FO_CRD_PIA",
    "FO_CRD_PLA",
    "FO_CRD_PLAD",
    "FO_CRD_PLC",
    "FO_CRD_PLO",
    "FO_CRD_REJ",
    "FO_CRD_RET",
    "FO_CRD_RFC",
    "FO_CRD_RFD",
    "FO_CRD_RSCH",
    "FO_CRD_SCD",
    "FO_CRD_SCR",
    "FO_CRD_SPAD",
    "FO_CRD_SPLA",
    "FO_CRD_SPLC",
    "FO_CRD_SPLO",
    "FO_CRD_TDR",
    "FO_CRD_TIC",
    "FO_CRD_WOF",
    "FO_CSH_BMOV",
    "FO_CSH_DNM",
    "FO_CSH_MOV",
    "FO_CTM_APR",
    "FO_CTM_CAC",
    "FO_CTM_CAS",
    "FO_CTM_CCN",
    "FO_CTM_CPN",
    "FO_CTM_EKYC",
    "FO_CTM_IKKC",
    "FO_CTM_IKYC",
    "FO_CTM_SEC",
    "FO_CTM_UKYC",
    "FO_DAT_TFER",
    "FO_DAT_TRF",
    "FO_DPT_ADJ_LIMIT_OD",
    "FO_DPT_ALA",
    "FO_DPT_AOPC",
    "FO_DPT_AOPM",
    "FO_DPT_AOPT",
    "FO_DPT_APR",
    "FO_DPT_AWDP",
    "FO_DPT_AWWR",
    "FO_DPT_BLK",
    "FO_DPT_CAS",
    "FO_DPT_CAS_OD",
    "FO_DPT_CCD",
    "FO_DPT_CCI",
    "FO_DPT_CCR",
    "FO_DPT_CCW",
    "FO_DPT_CDP",
    "FO_DPT_CDT",
    "FO_DPT_CEI",
    "FO_DPT_CER",
    "FO_DPT_CIP",
    "FO_DPT_CIQ",
    "FO_DPT_CIS",
    "FO_DPT_CIT",
    "FO_DPT_CLS",
    "FO_DPT_COD",
    "FO_DPT_COG",
    "FO_DPT_CRT",
    "FO_DPT_CSA",
    "FO_DPT_CSC",
    "FO_DPT_CSD",
    "FO_DPT_CSL",
    "FO_DPT_CSN",
    "FO_DPT_CSO",
    "FO_DPT_CSS",
    "FO_DPT_CSU",
    "FO_DPT_CTS",
    "FO_DPT_CWC",
    "FO_DPT_CWM",
    "FO_DPT_CWMB",
    "FO_DPT_CWR",
    "FO_DPT_CWT",
    "FO_DPT_DAS",
    "FO_DPT_DIP",
    "FO_DPT_DLS",
    "FO_DPT_DMN",
    "FO_DPT_DOD",
    "FO_DPT_DPT",
    "FO_DPT_EMK",
    "FO_DPT_ERL",
    "FO_DPT_EWDP",
    "FO_DPT_EWWR",
    "FO_DPT_EXT_TENOR_OD",
    "FO_DPT_FBI",
    "FO_DPT_FEE",
    "FO_DPT_FOC",
    "FO_DPT_HIS",
    "FO_DPT_IAJ_OD",
    "FO_DPT_IFC",
    "FO_DPT_IPR",
    "FO_DPT_LIDP",
    "FO_DPT_LIWR",
    "FO_DPT_MDC",
    "FO_DPT_MDP",
    "FO_DPT_MIP",
    "FO_DPT_MLS",
    "FO_DPT_MSW",
    "FO_DPT_MWR",
    "FO_DPT_MWT",
    "FO_DPT_NPL_OD",
    "FO_DPT_OCC",
    "FO_DPT_OCR",
    "FO_DPT_ODA",
    "FO_DPT_ODO",
    "FO_DPT_OPAL",
    "FO_DPT_OPC",
    "FO_DPT_OPM",
    "FO_DPT_OPN",
    "FO_DPT_OPSW",
    "FO_DPT_OPT",
    "FO_DPT_PIA",
    "FO_DPT_POI",
    "FO_DPT_POW",
    "FO_DPT_RADR",
    "FO_DPT_RCC",
    "FO_DPT_RCTM",
    "FO_DPT_RDP",
    "FO_DPT_REC",
    "FO_DPT_REJ",
    "FO_DPT_REJ_OD",
    "FO_DPT_RLS",
    "FO_DPT_RPO",
    "FO_DPT_SAB",
    "FO_DPT_SAL",
    "FO_DPT_SAT",
    "FO_DPT_SBI",
    "FO_DPT_SLS",
    "FO_DPT_SRA",
    "FO_DPT_SRG",
    "FO_DPT_TIR",
    "FO_DPT_TRF",
    "FO_DPT_TRT",
    "FO_DPT_ULCI",
    "FO_DPT_WDM",
    "FO_DPTDDCH",
    "FO_DPTDDGL",
    "FO_DPTDGCH",
    "FO_DPTGLDD",
    "FO_EMS_SICLS",
    "FO_EMS_STANDINGORDER",
    "FO_F3",
    "FO_FAC_ANB",
    "FO_FAC_CED",
    "FO_FAC_CLS",
    "FO_FAC_DEP",
    "FO_FAC_OPN",
    "FO_FAC_PBC",
    "FO_FAC_PBD",
    "FO_FAC_PBG",
    "FO_FAC_SBC",
    "FO_FAC_SBD",
    "FO_FAC_SBG",
    "FO_FAC_TFB",
    "FO_FEE",
    "FO_FOREX",
    "FO_MTG_APR",
    "FO_MTG_BLK",
    "FO_MTG_BRL",
    "FO_MTG_CLS",
    "FO_MTG_DCR",
    "FO_MTG_HDT",
    "FO_MTG_INR",
    "FO_MTG_KPT",
    "FO_MTG_KRL",
    "FO_MTG_OPN",
    "FO_MTG_REA",
    "FO_MTG_RLS",
    "FO_MTG_RPL",
    "FO_MTG_RTN",
    "FO_MTG_SCR",
    "FO_MTG_SPL",
    "FO_PMT_APR",
    "FO_PMT_APR2",
    "FO_PMT_APR3",
    "FO_PMT_IADT",
    "FO_PMT_IDT",
    "FO_PMT_IIT",
    "FO_PMT_IITT",
    "FO_PMT_KITT",
    "FO_PMT_ODT",
    "FO_PMT_ODTF",
    "FO_PMT_OFTA",
    "FO_PMT_OICT",
    "FO_PMT_OIT",
    "FO_PMT_OITA",
    "FO_PMT_OITT",
    "FO_PMT_PRO",
    "FO_PMT_REJ",
    "FO_PMT_REJ3",
    "FO_SCF_DDS",
    "FO_TFX_FAC",
    "FO_TFX_FCA",
    "FO_TFX_OAA",
    "FO_TFX_OFO",
    "FO_TMM_AAI",
    "FO_TMM_APP",
    "FO_TMM_DEP",
    "FO_TMM_HIS",
    "FO_TMM_IAD",
    "FO_TMM_ICL",
    "FO_TMM_IRP",
    "FO_TMM_OPN",
    "FO_TMM_PMA",
    "FO_TMM_WCD",
    "FO_TMM_WCP",
    "FO_TRD_ACLS",
    "FO_TRD_BBA",
    "FO_TRD_BBC",
    "FO_TRD_BBCT",
    "FO_TRD_BCC",
    "FO_TRD_BCL",
    "FO_TRD_BCN",
    "FO_TRD_BCNL",
    "FO_TRD_BCR",
    "FO_TRD_BCUL",
    "FO_TRD_BDD",
    "FO_TRD_BDR",
    "FO_TRD_BEX",
    "FO_TRD_BIV",
    "FO_TRD_BPG",
    "FO_TRD_BPM",
    "FO_TRD_BRA",
    "FO_TRD_CAA",
    "FO_TRD_CAS",
    "FO_TRD_CCL",
    "FO_TRD_CCN",
    "FO_TRD_CDD",
    "FO_TRD_CEX",
    "FO_TRD_CIV",
    "FO_TRD_CMT",
    "FO_TRD_CPM",
    "FO_TRD_CRD",
    "FO_TRD_DSN",
    "FO_TRD_FAD",
    "FO_TRD_FCC",
    "FO_TRD_GAD",
    "FO_TRD_GSC",
    "FO_TRD_HOA",
    "FO_TRD_IAM",
    "FO_TRD_IAV",
    "FO_TRD_ICF",
    "FO_TRD_ICL",
    "FO_TRD_IIR",
    "FO_TRD_IIT",
    "FO_TRD_IOT",
    "FO_TRD_IRA",
    "FO_TRD_ITA",
    "FO_TRD_NEG",
    "FO_TRD_OAJ",
    "FO_TRD_OAR",
    "FO_TRD_OAV",
    "FO_TRD_OCC",
    "FO_TRD_OCL",
    "FO_TRD_OCR",
    "FO_TRD_OCS",
    "FO_TRD_OLI",
    "FO_TRD_OLM",
    "FO_TRD_OLN",
    "FO_TRD_OLV",
    "FO_TRD_OPAL",
    "FO_TRD_ORN",
    "FO_TRD_OTE",
    "FO_TRD_OTV",
    "FO_TRD_PTR",
    "FO_TRD_RGD",
    "FO_TRD_RSC",
    "FO_TRD_SBX",
    "FO_TRD_SCL",
    "FO_TRD_SIC",
    "FO_TRD_SIR",
    "FO_TRD_SIV",
    "FO_TRD_SNI",
    "FO_TRS_OPAL"
];
const groupedFiles = {};
let formPrefix = "";
formDataChange.forEach(function (file) {
    let fileContents = fs.readFileSync(pathRawForms + "/" + file).toString();
    try {
        const jsonFileContents = JSON.parse(fileContents);
        const formContents = jsonFileContents[2].data[0];
        const formId = formContents.form_id;
        if (formContents && formContents.form_id) {
            if (isValidFormFO(formId)) {
                const currentFormId = formContents.form_id.toUpperCase();
                let foundGroup = false;
                for (const prefix of mainFormIdPrefixes) {
                    formPrefix = prefix;
                    if (currentFormId.startsWith(prefix)) {
                        if (!groupedFiles[prefix]) {
                            groupedFiles[prefix] = [];
                        }
                        groupedFiles[prefix].push(...jsonFileContents[2].data);
                        foundGroup = true;
                        break;
                    }
                }
                if (!foundGroup) {
                    if (!groupedFiles["other"]) {
                        groupedFiles["other"] = [];
                    }
                    groupedFiles["other"].push(...jsonFileContents[2].data);
                }
            }
        }
    } catch (error) {
        console.error("Error: ", error);
    }
});

for (const groupName in groupedFiles) {
    if (Object.prototype.hasOwnProperty.call(groupedFiles, groupName)) {
        fs.writeFile(pathInputForms + "/" + groupName + ".json", JSON.stringify(groupedFiles[groupName], null, 4), function (err) {
            if (err) throw err;
        });
    }
}
console.info("Input Forms converted!");