import pandas as pd
# ======================== SERVER 101 ========================
# IP = "27.3.1.101"
# IP_DB = "27.3.1.101"
# WORKING_DATE = "2027-01-01T00:00:00"
# OPENAPI_URL = "https://27.3.1.101:5017/api/workflow/"
# ======================== SERVER 104 ========================
# IP = "27.3.1.104"
# IP_DB = "27.3.1.104"
# WORKING_DATE = "2023-09-13T00:00:00"
# OPENAPI_URL = "https://test-cbs.shwesit.jits.digital/api/workflow/"
# ======================== SERVER 198 ========================
IP = "27.3.1.198"
IP_DB = "27.3.1.199"
WORKING_DATE = "2023-10-05T00:00:00"
OPENAPI_URL = "https://27.3.1.198:5017/api/workflow/"
# ======================== SERVER 109 ========================
# IP = "27.3.1.109"
# IP_DB = "27.3.1.109"
# WORKING_DATE = "2027-03-20T00:00:00"
# OPENAPI_URL = "https://27.3.1.109:5017/api/workflow/"
# ======================== SERVER 117 ========================
# IP = "27.3.1.117"
# IP_DB = "27.3.1.117"
# WORKING_DATE = "2027-01-01T00:00:00"
# OPENAPI_URL = "https://27.3.1.117:5017/api/workflow/"
# ======================== COMMON ========================
NEPTUNE_URL = "https://"+IP+":5001/"
NEPTUNE_LOGINNAME = "neptune"
NEPTUNE_PASSWORD = "123456"
WORKING_DATE_DB = pd.Timestamp(WORKING_DATE)
USER_LOGIN = {
    "user1": {
        "username": "cashier003",
        "password": "Sh@123456",
        "branch_code": "003",
        "fullname": "Cashier 003",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user2": {
        "username": "cashier002",
        "password": "Sh@123456",
        "branch_code": "002",
        "fullname": "Cashier 002",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user3": {
        "username": "cashier004",
        "password": "Sh@123456",
        "branch_code": "004",
        "fullname": "Cashier 004",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user4": {
        "username": "cashier005",
        "password": "Sh@123456",
        "branch_code": "005",
        "fullname": "Cashier 005",
        "working_date": WORKING_DATE,
    },
    "user5": {
        "username": "cashier006",
        "password": "Sh@123456",
        "branch_code": "006",
        "fullname": "Cashier 006",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user6": {
        "username": "ac03",
        "password": "123456",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user7": {
        "username": "cardzone01",
        "password": "Ocar@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user8": {
        "username": "digital01",
        "password": "Zdig@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user9": {
        "username": "paygate01",
        "password": "Dpay@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user10": {
        "username": "cardzone02",
        "password": "Ocar@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user11": {
        "username": "momoney01",
        "password": "Pmom@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user12": {
        "username": "cbmnet01",
        "password": "Bcbm@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user13": {
        "username": "bill01",
        "password": "Nbil@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user14": {
        "username": "mpusettle01",
        "password": "Qmpu@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user15": {
        "username": "cheque01",
        "password": "Uche@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    },
    "user16": {
        "username": "los01",
        "password": "Llos@123",
        "branch_code": "",
        "fullname": "",
        "working_date": WORKING_DATE,
        "working_date_db": WORKING_DATE_DB,
    }
}
SERVICE_URL = {
    # "adm": "http://" + IP + ":8051/",
    "adm": "https://" + IP + ":5013/",
    "ctm": "https://" + IP + ":8054/",
    "act": "https://" + IP + ":8050/",
    "csh": "https://" + IP + ":8052/",
    "crd": "https://" + IP + ":8053/",
    "dpt": "https://" + IP + ":8055/",
    "fac": "https://" + IP + ":8056/",
    "fx": "https://" + IP + ":8057/",
    "ifc": "https://" + IP + ":8058/",
    "mtg": "http://" + IP + ":8059/",
    "pmt": "https://" + IP + ":8060/",
}
DB_INFO = {
    "server": IP_DB + ",1433",
    "username": "sa",
    "password": "123456"
}
# token 179
# STATIC_TOKEN_NEPTUNE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOZXB0dW5lIGFkbWluaXN0cmF0b3IiLCJqdGkiOiIxMWRiY2E1ZC0yMmJhLTRiNDItOTVlOS1mYThlYjI2NmQ5MGUiLCJhdXRoX3RpbWUiOiIxNjc0MDEyMTU1ODUzIiwidWlkIjoiZTI2MTAxOGY0NzAzNGRiOWIwZjM5NGI4OWFkYmIyMTQiLCJvaWQiOiIxODliZTk5NzU5ZDU0NDZjODAwZTZiNjIwNjUyZTMxYSIsImxhbmciOiJlbiIsInJvbGVzIjoiQURNSU5JU1RSQVRPUiIsImV4cCI6MTcwNTU0ODE1NSwiaXNzIjoiSnVzdC1Jbi1UaW1lIFNvbHV0aW9ucyBKU0MiLCJhdWQiOiJOZXB0dW5lIn0.xrttEe0i-2Y0NcIZYdMUVzRi1rzuK1YbHOLjxkgYdic"
# token 104
STATIC_TOKEN_NEPTUNE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOZXB0dW5lIGFkbWluaXN0cmF0b3IiLCJqdGkiOiIzZGQ1MDdkNi1jNjk5LTQ4MmUtODAzYS00NTYwYjAxMDg1ZTEiLCJhdXRoX3RpbWUiOiIxNzM2MjUxNTYwNDA0IiwidWlkIjoiZTI2MTAxOGY0NzAzNGRiOWIwZjM5NGI4OWFkYmIyMTQiLCJvaWQiOiIxODliZTk5NzU5ZDU0NDZjODAwZTZiNjIwNjUyZTMxYSIsImxhbmciOiJlbiIsInJvbGVzIjoiQURNSU5JU1RSQVRPUiIsImV4cCI6MTczNjI2MTE2MCwiaXNzIjoiSnVzdC1Jbi1UaW1lIFNvbHV0aW9ucyBKU0MiLCJhdWQiOiJOZXB0dW5lIn0.4xteRLbXIleoyjuKrGkCLsnwYmg83tVTX7VWbPZ2ORo"
STATIC_TOKEN_CZ = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDYXJkem9uZSBhZG1pbmlzdHJhdG9yIiwianRpIjoiMTlhNDM4MDUtNTIxNy00ZTE3LWFkMTgtMDMxODRhNmZiNmMzIiwiYXV0aF90aW1lIjoiMTY5Mjk0MTI1NTcyOSIsInVpZCI6IjI1YjY0MmJlY2YyZTRkMDI4MDczYTZhNjZkODQxMjlhIiwib2lkIjoiMTg5YmU5OTc1OWQ1NDQ2YzgwMGU2YjYyMDY1MmUzMWEiLCJsYW5nIjoiZW4iLCJyb2xlcyI6WyJDQVJEWk9ORSIsIkVYRUNVVE9SIl0sImV4cCI6MTc3OTM0MTI1NSwiaXNzIjoiSnVzdC1Jbi1UaW1lIFNvbHV0aW9ucyBKU0MiLCJhdWQiOiJOZXB0dW5lIn0.pc7c9DP5c1dlIOOw_MoeoavfKa2tWS_WDUepvm4c__k"
STATIC_TOKEN_MO = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNb21vbmV5IGFkbWluaXN0cmF0b3IiLCJqdGkiOiJlMDFlYTZlMi02MjE2LTQwMTctOTcxMC1lZGZmNmViZDgxZWMiLCJhdXRoX3RpbWUiOiIxNjkyOTQxMjY1MTk1IiwidWlkIjoiMjRiZmMwYmNmMmE5NDIyNTkyZWFkNThkZGQ3YWRhNjYiLCJvaWQiOiIxODliZTk5NzU5ZDU0NDZjODAwZTZiNjIwNjUyZTMxYSIsImxhbmciOiJlbiIsInJvbGVzIjpbIkVYRUNVVE9SIiwiTU9NT05FWSJdLCJleHAiOjE3NzkzNDEyNjUsImlzcyI6Ikp1c3QtSW4tVGltZSBTb2x1dGlvbnMgSlNDIiwiYXVkIjoiTmVwdHVuZSJ9.1R1jkAbO9GQMM8Y81xkW9kXpp9G4I57xUARB_fitwIg"

EXPECTED_KEY = {
    'level_01': [
        'status',
        'data',
        'error_message',
        'error_code',
    ],
    'postings': [
        'TransactionNumber',
        'TransTableName',
        'TransId',
        'SysAccountName',
        'GLAccount',
        'DorC',
        'TransactionStatus',
        'Amount',
        'BranchCode',
        'CurrencyCode',
        'ValueDate',
        'Posted',
        'AccountingGroup',
        'CrossBranchCode',
        'CrossCurrencyCode',
        'BaseCurrencyAmount',
        'Id',
    ],
    'fee_data': [
        'ifc_name',
        'share_fee',
        'ifc_code',
        'payrate',
        'ifc_value',
        'ifc_amount',
        'currency_account_code',
        'floor_value',
        'ceiling_value',
        'share_rate',
        'share_amount',
        'round_rate',
        'round_amount',
        'currency_fee_code',
        'pay_source',
        # 'value_typect', #C#
        'value_type',
    ],
    'data_step_cash': [
        'list_cash',
        'list_cash_from_response',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
    ],
    'data_list_cash': [
        'amount_cash_change',
        'base_amount',
        'debit_or_credit',
        'currency_code',
        'condition',
        'posting',
        'accounting_group',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
    ],
    'account_balances': [
        'account_number',
        'amount',
        'debit_or_credit',
        'currency',
        'available_balance',
        'transaction_number',
        'transaction_date',
        'description',
    ],
    'data_dpt_opn': [
        # 'id', #C#
        # 'master_f_d_account', #C#
        # 'user_created', #C#
        # 'branch_code', #C#
        # 'ifc_balances', #C#
        # 'currency_code', #C#
        # 'language', #C#
        # 'channel_id', #C#
        # 'trans_id', #C#
        # 'request_body', #C#
        # 'is_batch', #C#
        # 'is_system', #C#
        # 'is_force_reverse', #C#
        # 'postings', #C#
        # 'ignore_session', #C#
        'account_number',
        'customer_type',
        'customer_code',
        'catalog_code',
        'catalog_name',
        'deposit_type',
        'deposit_sub_type',
        'deposit_purpose',
        'account_type',
        'seq_number',
        'account_name',
        'business_purpose_code',
        'rollover',
        'auto_transfer_option',
        'to_account_number',
        'branch_name',
        'agent_hub_referral',
        'relation_customers',
        'account_chart_number',
        'employer_organization_name',
        'is_restricted',
        'im_banking',
        'pc_book',
        'mpu_card',
        'wallet',
        'extension_fields',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        'reason_of_account_opening',
        'relationship_manager',
        'master_fd_account', #stored
        'customer_info', #stored
    ],
    'data_dpt_opn_extension_fields': [
        'reason_of_account_opening',
        'relationship_manager'
    ],
    'data_dpt_apr': [
        'account_number',
        'account_holder_name',
        'branch_name',
        'catalog_code',
        'account_type',
        'catalogue_name',
        'deposit_type',
        'deposit_sub_type',
        'created_by',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
    ],
    'data_dpt_cdp': [
        'account_number',
        'amount_deposit',
        'amount',
        'depositor_description',
        'inclusive',
        'depositor_address',
        'identification_number',
        'currency_deposit',
        'values_date',
        'customer_code',
        'cash_amount_bcy',
        'id_place',
        'cash_exchange_rate',
        'cash_amount',
        'cash_currency',
        'prepaid_interest',
        'account_name',
        'exchange_rate',
        'cross_rate',
        'deposit_type',
        'interest_tenor_unit',
        'commission',
        'id_issue_date',
        'base_amount', #failed
        'total_ifc_fee', #failed
        'fee_currency_code', #failed
        'round_total_ifc_fee',
        'branch_name',
        'fee_data',
        # 'account_balances', #C#
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        'short_currency_id', #stored
    ],
    'data_dpt_cdp_depositor_description': [
        'home',
        'office',
    ],
    'data_dpt_mdp': [
        'account_number',
        'amount_deposit',
        'debit_accounting',
        'accounting_currency',
        'cross_rate',
        'acounting_amount',
        'exchange_rate_of_accounting_bcy',
        'accounting_amount_bcy',
        'depositor_name',
        'depositor_code',
        'depositor_address',
        'depositor_description',
        'values_date',
        'deposit_currency',
        'exchange_rate_debit_account_bcy',
        'amount_debit_account_bcy',
        'prepaid_interest',
        'accounting_currency1',
        'fee_data',
        'total_fee',
        'branch_name',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        # 'short_currency_id', #stored
    ],
    'data_dpt_mdp_depositor_description': [
        'home',
        'office',
    ],
    'data_dpt_cwr': [
        'account_number',
        'customer_code',
        'current_balance',
        'available_balance',
        'withdraw_amount',
        'cash_currency',
        'cross_rate',
        'cash_amount',
        'exchange_rate',
        'cash_amount_bcy',
        'withdrawer_name',
        'withdrawer_id',
        'withdrawer_address',
        'withdrawer_description',
        'id_issue_date',
        'id_place',
        'identification_number',
        'currency_of_deposit_account',
        'exchange_rate_debit_account_bcy',
        'amount_debit_account_bcy',
        'interest_from_earlywdr',
        'due_date',
        'commission',
        'interest_prepaid',
        'total_vat_for_cash',
        'account_linkage',
        'amount_linkage',
        'branch_name',
        'total_ifc_fee_cash',
        'total_ifc_fee_deposit',
        'total_ifc_fee',
        'fee_currency_code',
        'passbook_number',
        'fee_data',
        # 'account_balances', #C#
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        'short_currency_id', #stored
    ],
    'data_dpt_cwr_withdrawer_description': [
        'home',
        'office',
    ],
    'data_dpt_cwr_account_balances': [
        'account_number',
        'amount',
        'debit_or_credit',
        'currency',
        'available_balance',
        'transaction_number',
        'transaction_date',
        'description',
    ],
    'data_dpt_mwr': [
        'account_number',
        'current_balance',
        'available_balance',
        'interest_prepaid',
        'interest_earlywdr',
        'withdraw_amount',
        'credit_accounting',
        'accounting_currency',
        'cross_rate',
        'accounting_amount',
        'exchange_rate_of_accounting_bcy',
        'amount_equivalent_in_bcy',
        'withdrawer_name',
        'withdrawer_code',
        'withdrawer_address',
        'withdrawer_description',
        'values_date',
        'currency_of_deposit_account',
        'exchange_rate_debit_account_bcy',
        'amount_debit_account_bcy',
        'account_linkage',
        'amount_linkage',
        'branch_code',
        'branch_name',
        'fee_data',
        'total_ifc_fee_accounting',
        'total_ifc_fee_deposit',
        'total_ifc_fee',
        'passbook_number',
        # 'account_balances', #C#
        'auto_fund_trasfer',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        'short_currency_id', #stored
    ],
    'data_dpt_mwr_withdrawer_description': [
        'home',
        'office',
    ],
    'data_dpt_trf': [
        'debit_account',
        'customer_code_debit',
        'balance_debit_account',
        'available_balance_debit_account',
        'account_linkage',
        'amount_linkage',
        'amount',
        't_exchange_rate_debit_account_bcy',
        'amount_equivalent_in_bcy',
        'credit_account',
        'customer_code_credit',
        'currency_of_debit_account',
        'currency_of_credit_account',
        'cross_rate',
        'credit_amount',
        'exchange_rate_credit_ac_bcy',
        'amount_to_credit_bcy',
        'debit_account_name',
        'customer_code',
        'customer_address',
        'customer_description',
        'total_fee_credit_account',
        'paper_number_of_debit',
        'issue_date_of_debit',
        'total_amount_payable',
        'issue_place_of_debit',
        'paper_number_of_credit',
        'issue_date_of_credit',
        'total_fee',
        'fee_currency_code',
        'issue_place_of_credit',
        'credit_account_name',
        'b_exchange_rate_debit_account_bcy',
        'amount_debit_account_bcy',
        'branch_name',
        'passbook_number',
        'fee_data',
        'total_ifc_fee',
        'prepaid_interest',
        'auto_fund_trasfer',
        # 'account_balances', #C#
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        'short_currency_id', #stored
    ],
    'data_dpt_trf_customer_description': [
        'home',
        'office',
    ],
    'data_dpt_cwc': [
        'stock_prefix',
        'cheque_no',
        'account_number',
        'current_balance',
        'available_balance',
        'cheque_amount',
        'cash_currency',
        'cross_rate',
        'cash_amount',
        'exchange_rate',
        'cash_amount_bcy',
        'withdrawer_name',
        'withdrawer_id',
        'withdrawer_address',
        'withdrawer_description',
        'id_issue_date',
        'id_place',
        'identification_number',
        'currency_of_deposit_account',
        'exchange_rate_debit_account_bcy',
        'amount_debit_account_bcy',
        'commission',
        'interest_from_earlywdr',
        'due_date',
        'interest_prepaid',
        'total_vat_for_cash',
        'account_linkage',
        'amount_linkage',
        'branch_name',
        'fee_data',
        'total_ifc_fee_cash',
        'total_ifc_fee_deposit',
        # 'account_balances', #C#
        'auto_fund_trasfer',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        'short_currency_id', #stored
    ],
    'data_dpt_cwc_withdrawer_description': [
        'home',
        'office',
    ],
    'data_dpt_sbi': [
        'stock_type',
        'account_number',
        'serial_no',
        'stock_prefix',
        'method',
        'account_number_for_fee',
        'currency_code',
        'branch_name',
        'total_fee',
        'fee_data',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        'short_currency_id', #stored
        'ref_branch_code', #stored
    ],
    'data_dpt_fbi': [
        'stock_type',
        'account_number',
        'serial_no',
        'stock_prefix',
        'method',
        'account_number_for_fee',
        'currency_code',
        'branch_name',
        'total_fee',
        'fee_data',
        'transaction_code',
        'transaction_number',
        'transaction_type',
        'sub_code',
        'transaction_date',
        'service_sys_date',
        'reference_id',
        'ref_id',
        'reference_code',
        'business_code',
        'value_date',
        'current_user_code',
        'current_branch_code',
        'current_username',
        'current_loginname',
        'user_approve',
        'status',
        'is_reverse',
        'amount1',
        'description',
        'token',
        'is_transaction_reverse',
        'is_transaction_compensated',
        # 'short_currency_id', #stored
        # 'ref_branch_code', #stored
    ]
}

EXPECTED_COL = {
    'DepositAccount_approve': [
        'LastTransactionDate',
        'DepositStatus',
        'Psts',
        'UserApproved',
        'UpdatedOnUtc',
    ],
    'DepositAccount_status': [
        
    ],
    'DepositAccount_deposit_new': [
        'DepositAmount',
        'CurrentBalance',
        'Psts',
        'WeekCredit',
        'MonthCredit',
        'QuarterCredit',
        'SemiAnnualCredit',
        'YearCredit',
        'UpdatedOnUtc',
        'LastTransactionDate',
        'DepositStatus',
    ],
    'DepositAccount_deposit_normal': [
        'DepositAmount',
        'CurrentBalance',
        # 'Psts', #C#
        'WeekCredit',
        'MonthCredit',
        'QuarterCredit',
        'SemiAnnualCredit',
        'YearCredit',
        'UpdatedOnUtc',
        'LastTransactionDate',
    ],
    'DepositAccount_deposit_fixed_deposit': [
        'DepositAmount',
        'CurrentBalance',
        'Psts',
        'WeekCredit',
        'MonthCredit',
        'QuarterCredit',
        'SemiAnnualCredit',
        'YearCredit',
        'UpdatedOnUtc',
        'LastTransactionDate',
        'DepositStatus',
        'EndOfTenor',
        'BeginOfTenor',
    ],
    'DepositAccount_deposit_prepaid_fixed_deposit': [
        'DepositAmount',
        'CurrentBalance',
        'Psts',
        'WeekCredit',
        'MonthCredit',
        'QuarterCredit',
        'SemiAnnualCredit',
        'YearCredit',
        'UpdatedOnUtc',
        'LastTransactionDate',
        'DepositStatus',
        'EndOfTenor',
        'BeginOfTenor',
        'Intpre',
    ],
    'DepositAccount_withdraw': [
        
    ],
    'IFCBalance_deposit_prepaid_fixed_deposit': [
        'UpdatedOnUtc',
        'PrepaidAmount',
        'LastDatetime',
    ],
    'CashList': [
        'CurrentBalance',
        'UpdatedOnUtc',
    ],
    'CashStatement': [
        'CashAmount',
        'UpdatedOnUtc',
    ],
    'AccountBalance_credit': [
        'Balance',
        'DailyCredit',
        'WeeklyCredit',
        'MonthlyCredit',
        'QuarterlyCredit',
        'HalfYearlyCredit',
        'YearlyCredit',
    ],
    'AccountBalance_debit': [
        'Balance',
        'DailyDebit',
        'WeeklyDebit',
        'MonthlyDebit',
        'QuarterlyDebit',
        'HalfYearlyDebit',
        'YearlyDebit',
    ],

}